### ISSUE TITLE
List of all leftovers problems in sprint 2 

### ISSUE THREAD

**Issue by Jood80** [NextUp-comedy/api-nc#36]
### To be fixed:
- [x] #37
- [x] unify the sent message to the user when signup to be `user does not exist` instead of exposing his/her current status `PENDING | REJECT | APPROVED` in `registrationChecks`
- [ ] handle reason of rejection coming from the front to `api/v1/user/reject/:id`
- [ ] handle waitingList pagination
- [ ] validate the email to follow a regex & handle the validation error to be sent to the front through a msg.
- [ ] change the sent message when the user enter their already approved email to be something else than that `CHECK EMAIL` to distinguish it from other messages.
- [ ] handle this error occurred at Google login/signup process
    <img src="https://user-images.githubusercontent.com/56412800/185908990-0dc093b1-c8fe-4bb3-aab2-adffaf3dd17f.png" width=700 hieght=200 />
- [x] create controller for change password.
